FROM rhoerbe/docker-pvzd-pre
MAINTAINER r2h2 <rhoerbe@hoerbe.at>


# install MOCCA (requires GUI)
RUN curl -O http://webstart.buergerkarte.at/mocca/webstart/mocca.jnlp

ADD PVZD /PVZD
WORKDIR /PVZD/PolicyManager
RUN chmod +x /PVZD/PolicyManager/tests/PMPTestNosign.sh /PVZD/PolicyManager/tests/PAtool.sh

# required to run unit tests
ADD pycharm-helper /pycharm-helper

#ADD start.sh /start.sh
#RUN chmod a+x /start.sh
#CMD ["/start.sh"]

# Clean up yum when done.
#RUN yum -y clean all

