#!/bin/bash
#
# pyff_batch        Startup script for the pyff docker container with the md aggregator
# chkconfig: 345 84 16
# description: pyff SAML Metadata Aggregator
#
### BEGIN INIT INFO
# Provides: gunicorn/peer
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop docker container for pyff batch
### END INIT INFO

# Path definitions
prog='docker_pyff_batch'
RETVAL=0

start() {
        echo -n "Starting $prog: "
        if service docker status |grep -qv 'is running'; then
            waittime=5
            echo -n "(waiting ${waittime}s for docker daemon to complete startup)"
            sleep ${waittime}
        fi
        if service docker status |grep -qv 'is running'; then
            echo
            echo "docker not running - cannot start container"
        else
            /opt/pyff_batch/docker_run.sh -d
            echo
        fi
        return 0
}

stop() {
    if ${sudo} docker ps | awk '{print $NF}' | grep -qx pyff_batch; then
        echo -n "stopping ${prog}"
        /opt/pyff_batch/docker_stop.sh
        # ${sudo} docker kill ${name}  # should not be necessary
        echo
    else
        echo "${prog} is not running"
    fi
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|help}"
        RETVAL=2
esac

exit $RETVAL

